AllCops:
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
